server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: debug
jwt:
  secret: ${SECRET_KEY}

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: accounts-pwb
          uri: http://accounts-pwb:8200/
          predicates:
            - Path=/accounts/**
        - id: transaction-pwb
          uri: http://transaction-pwb:8300/
          predicates:
            - Path=/transactions/**
        - id: authentication-pwb
          uri: http://authentication-pwb:8100/
          predicates:
            - Path=/auth/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "**"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS



